services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: medusa_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB} # 新增环境变量
      POSTGRES_USER: ${POSTGRES_USER} # 新增环境变量
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} # 新增环境变量
    #railway不允许暴露端口
    #ports:
    #  - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - medusa_network

  # Redis
  redis:
    image: redis:7-alpine
    container_name: medusa_redis
    restart: unless-stopped
    #railway不允许暴露端口
    #ports:
    #  - "6379:6379"
    # 新增 volumes 配置，将 Redis 数据目录挂载到命名卷
    volumes:
      - redis_data:/data
    networks:
      - medusa_network

  # Medusa Server
  # This service runs the Medusa backend application
  # and the admin dashboard.
  medusa:
    build: .
    container_name: medusa_backend
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    ports:
      - "9000:9000"
    environment:
      - NODE_ENV=production
      # 将硬编码的DATABASE_URL替换为变量引用，从.env文件读取
      - DATABASE_URL=${DATABASE_URL}  # 关键修改：使用${变量名}引用.env中的DATABASE_URL
      - REDIS_URL=${REDIS_URL}  # 新增这行，引用 .env 中的 Redis 地址
    env_file:
      - .env
    # 删除以下两行开发用的 volumes 配置  
    #volumes:
    #  - .:/app
    #  - /app/node_modules
    networks:
      - medusa_network

volumes:
  postgres_data:
  redis_data:  # 新增 Redis 数据卷
networks:
  medusa_network:
    driver: bridge